[package]
name = "ignis"
description = "Simple and fast JVM"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.1"
bumpalo = { version = "3.19.0", features = ["collections"] }
cesu8 = "=1.1.0"
thiserror = "2.0.12"
